// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSe1PKwPqxQQc4k4ozTlFrifz9WiuVpP4',
    appId: '1:412289997343:web:217fbe2aee587a9196532a',
    messagingSenderId: '412289997343',
    projectId: 'crypto-list-app-6b855',
    authDomain: 'crypto-list-app-6b855.firebaseapp.com',
    storageBucket: 'crypto-list-app-6b855.appspot.com',
    measurementId: 'G-835D7V5G64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxybkWQI0QP9EFhZHw3m_ULHsU9Q0Kd-E',
    appId: '1:412289997343:android:814c8144b29700a096532a',
    messagingSenderId: '412289997343',
    projectId: 'crypto-list-app-6b855',
    storageBucket: 'crypto-list-app-6b855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPBNFe4Fc3xNTGkuhex9B72q_4ZyO-Njs',
    appId: '1:412289997343:ios:cba565bb2159885d96532a',
    messagingSenderId: '412289997343',
    projectId: 'crypto-list-app-6b855',
    storageBucket: 'crypto-list-app-6b855.appspot.com',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPBNFe4Fc3xNTGkuhex9B72q_4ZyO-Njs',
    appId: '1:412289997343:ios:caeef965960fb22a96532a',
    messagingSenderId: '412289997343',
    projectId: 'crypto-list-app-6b855',
    storageBucket: 'crypto-list-app-6b855.appspot.com',
    iosBundleId: 'com.example.flutterProjects.RunnerTests',
  );
}
